version: "3.3"
services:
  db:
    build:
      context: ./db
      dockerfile: db.dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  init-db:
    volumes:
      - ./restapi:/code
    env_file:
      - .env
    build:
      context: ./restapi
      dockerfile: restapi.dockerfile
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
  keycloak:
    build:
      context: ./keycloak
      dockerfile: keycloak.dockerfile
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_IMPORT=/root/test-realm.json
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8080"]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
  restapi:
    ports:
      - "8888:8888"
    volumes:
      - ./restapi:/code
    env_file:
      - .env
    build:
      context: ./restapi
      dockerfile: restapi.dockerfile
    depends_on:
      init-db:
        condition: service_completed_successfully
      keycloak:
        condition: service_healthy
volumes:
  db-data:
