version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  init-db:
    volumes:
      - ./restapi:/code
    env_file:
      - .env
    build:
      context: ./restapi
      dockerfile: restapi.dockerfile
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
  restapi:
    ports:
      - "8888:8888"
    volumes:
      - ./restapi:/code
    env_file:
      - .env
    build:
      context: ./restapi
      dockerfile: restapi.dockerfile
    depends_on:
      init-db:
        condition: service_completed_successfully
volumes:
  db-data:
