"""add users

Revision ID: ac255cf5a177
Revises: 7adcc6fda540
Create Date: 2024-02-08 02:06:50.567670

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "ac255cf5a177"
down_revision: Union[str, None] = "7adcc6fda540"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("items", sa.Column("owner_id", sa.String(), nullable=False))
    op.add_column("items", sa.Column("data", sa.JSON(), nullable=False))
    op.create_foreign_key("items_owner_id_fkey", "items", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("items_owner_id_fkey", "items", type_="foreignkey")
    op.drop_column("items", "data")
    op.drop_column("items", "owner_id")
    op.drop_table("users")
    # ### end Alembic commands ###
